name: Deploy DrawToDigit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js env for frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Frontend: Install dependencies and build project
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Frontend: Deploy to S3
      - name: Deploy frontend to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-southeast-2"
        run: aws s3 sync frontend/build/ s3://drawtodigit-frontend --delete

      # Frontend: Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-southeast-2"
        run: |
          aws cloudfront create-invalidation --distribution-id E171B3KU2UL2VA --paths "/*"

      # Backend: Set up Python env
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Backend: Install dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/active
          pip install -r requirements.txt

      # Backend: Deploy to EC2
      - name: Deploy backend to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          # Save the SHH key to a file
          echo "${EC2_KEY}" | base64 -d > ~/drawtodigit.pem
          chmod 600 ~/drawtodigit.pem

          # Transfer backend files to EC2
          scp -o StrictHostKeyChecking=no -i ~/ec2-key.pem -r backend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/backend

          # Connect to EC2 and restart the backend server
          ssh -o StrictHostKeyChecking=no -i ~/ec2-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/backend
            source venv/bin/activate
            nohup python app.py &
          EOF
